### ISSUE TITLE
scope closures context

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#113]
https://trello.com/c/HIdlcB9A/13-scope-context-and-closures

**Comment by adambray** [comment]
+: Diagrams on scope were well-recieved, exercise for context was well-received, and set them up for success with homework (timer_js). Practical nature of scope and context lessons were well-received.

delta: had students do second scope diagram (displayPerson) instead of lab (cut out lab), need more time to cover closures, so it was glossed over. probably introduced too early for most. need at least one more good (complex) exercise for context.
