### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#207]
https://trello.com/c/taSfcKjF/19-workflows

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/0bee928767dc3b126e227dfda0c852c72715adb2/02-intermediate-front-end/workflows/lesson_plan.md

**Comment by andrewsunglaekim** [comment]
∆ wasn't able to cover one of my learning objectives(proof of concept). I think going forward it'd be nice for them to create an MVP proof of concept for a future project and generate user stories for it.

+ Felt the students really enjoyed the Airplane exercise, and it seemed to break up the monotony of an otherwise mundane block of content. Having two group activities and a short video clip helped alot.
