### ISSUE TITLE
Active Record

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#220]

**Comment by mattscilipoti** [comment]
delta: suggest dir structure for wdi & hospital “apps”.  Many students created `config` right in `sandbox`, instead of `wdi/config` or `hospital/config`.  Use `tree` frequently at start.
delta:  clarify separation of directory & database.  Maybe `wdi_ar/` or `hospital _app`?  After some discussion, I recommend we be pedantic and suffix our app and db (hospital_app, hospital_db).  We also recommend changing "wdi" to classroom_app.

delta: discuss the what and why BEFORE we do something, instead of explaining the step we just took.

I started doing this, but realized I should be spending this time on my upcoming lesson.  See branch ar_delta_mms: 8d6c763b6c04917eb84785433380b06e63616883.

**Comment by andrewsunglaekim** [comment]
Yeah, I was checking the database for CRUD requests, but yeah, should confirm steps along the way. I think I'd like to keep it the say i do you do structure as far as break points, but change the file structure. I think enough students we're having trouble with just the setup that I'd like to isolate each point of it.

I think one thing to note is that normally by this time students have more experience with CLI, so definitely should take note that file navigation is a bit tougher for students at this point.

Going to commit some changes tonight regarding file structure. Additionally great tip on explaining something before coding it. But sometimes I do like to reference the code in order to explain it in greater detail. 

I think overall the lesson went pretty well minus the discrepancies b/w folder/database. I enjoyed/got really excited about relating how these CRUD actions take place in the wild.

Thanks for the feedback matt!

**Comment by mattscilipoti** [comment]
Delta: Add .not: https://robots.thoughtbot.com/activerecords-wherenot
